### PR TITLE
Repost OTSconf mailing as blog article

### PR DESCRIPTION
**Pull request by lehmannro**
As sent out on Meetup, edited for generality.

### CODE REVIEW

**Comment by lehmannro** [comment]
@ligthyear please review. :-)

**Comment by lehmannro** [comment]
Removed the Hackership campaign.  Merge at your convenience.

**Comment by gnunicorn** [comment]
The campaign is over on the 10th... That's three days from now, but as you please.

**Comment by gnunicorn** [comment]
thanks, @lehmannro !

**Pull request merged**
