### PR TITLE
More meta tags

### LINKED ISSUE #27: Implement metatags
Read more about which ones are relevant and what to put on it here: http://blog.iacquire.com/2013/02/21/18-meta-tags-every-webpage-should-have-in-2013/

### PR DESCRIPTION
**Pull request by gnunicorn**
Implements and fixes #27 . Adding Meta-Tags for OpenGraph, Twitter and Google+ to make it easier share- and findable.

// cc @stefanhoth , @stevenfarlie

### CODE REVIEW

**Comment by gnunicorn** [comment]
Oh. And Facebook-Admins. Then we should be able to get insights on likes and stuff for articles, too I think.

**Comment by stefanhoth** [comment]
How about placing a hashmap (dictionary?) in the config for author name (or ots-account name)-> gplus-account mapping? This way the pages could just have the author name and we can add more stuff to that later on.

**Comment by gnunicorn** [comment]
@stefanhoth that sounds like a great idea. But I am not sure that is really possible with liquid-template-engine. I'll try to figure it out and come back with you.

**Comment by gnunicorn** [comment]
Ok. Messed up with the branch, but all should be back in order now. We are now using a pre-defined "authors" dictionary from the config. Much more smoother, thanks for the idea, @stefanhoth . Pls review again.

**Pull request merged**
