### PR TITLE
More author stuff:

### PR DESCRIPTION
**Pull request by gnunicorn**
Hey there,

that Authors-Dictionary-Idea set a spark in me and I made this following changes ontop., too. Making our blog a big more personal and also give credit to the authors:
- The dictionary now also contains an about-section, giving some context to the author
- the dictionary now also contains an image the author can link to
- the author is named, shown (picture) and the about is shown under their blog-posts (see screenshot)
- there is a /authors.html generated out of the config-section (see screenshot)
- the authors.html is linked in the footer of each page
- the author is propagated in the atom-feed

An example post by Amélie showing her name and about text:
6125b580-dc3b-47ac-9fa6-5b965ec70532

The Authors-Listing:
4073bd36-2845-4ec7-8661-40adf49ea9ea

This looks like a bunch of changes but after the meta-tags have been merged, there are only two or three commits to look at.

### CODE REVIEW

**Comment by gnunicorn** [comment]
@stefanhoth feedback?

**Comment by stefanhoth** [comment]
Awesome! But you should ask everyone to check for "their" text snippet.

**Comment by nekopanic** [comment]
looks good

**Comment by utstikkar** [comment]
Except for the one typo (it should be "appearances") I am happy with my description :).

**Pull request merged**
