### PR TITLE
adds "What OpenTechSchool brought to Dortmund" blog entry

### PR DESCRIPTION
**Pull request by ghost**
Hi there! I would like to contribute a new blog entry. It is about the work and events of the Dortmund chapter. Written from my personal point of view in which ways OTS had a positive impact towards the local community.

I hope you'll like it.

### CODE REVIEW

**Comment by tobmaster** [comment]
The blog entry is good. @ligthyear anything needed to be changed?

**Comment by ghost** [comment]
Hi Matt!

On 28 Feb 2014, at 05:46, Matt Iversen notifications@github.com wrote:

> If you have no description you don't need to include the tag. You've forgotten to close the headers with another ---. You've forgotten to close the teaser with a “.

Thank you for writing! This is my first blog entry for OTS ever. So I wrote my document similar to the last one “2014-02-07-taking-over-it-labs-berlin.md” written by Ben. He uses Multiline Description and Teaser sections in there. Is this forbidden?

I deleted the empty description section but I have opening and closing teaser and description sections in lines 12-17 and 19-24. The limiting triple dash is at line 27.

Do I have to inline the teaser/description contents in order to submit a valid document? Otherwise, the given criteria have been already fulfilled.

Thank you in advance, :)
Dennis

**Comment by Ivoz** [comment]
Hi, sorry, I think I was a bit tired. I saw the `---` later on.

Your image (`/assets/content/2014-02-17-ots-brought-to-dortmund/landmark-dortmund.jpg`) is missing. You've linked to it once in the header and once in the body.

You don't need another title in the body of the post, that already comes from the header title.

You're missing a corresponding entry for yourself in [_config.yml](https://github.com/snnd/blog.opentechschool.org/blob/gh-pages/_config.yml#L25). Hopefully its fairly obvious how to add yourself.

Have you tried building the blog yourself and previewing it? It helps with picking up all these :)

After that it should be good. Cheers

**Comment by ghost** [comment]
Thank you! I fixed that. Can we have merge now? :)

**Comment by Ivoz** [comment]
Sorry, it seems you're adding the same picture twice as `landmark-dortmund.jpg` and `teaser-dortmund.jpg`?

**Comment by ghost** [comment]
Yes, therefore i removed teaser-dortmund.jpg and checked the post for just having landmark-dortmund.jpg instead of teaser-dortmund.jpg. :)

**Pull request merged**
